### ISSUE TITLE
Reset notifications of data clear

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#90] opened 2020-07-02 16:36 UTC
The 'clear all data' doesn't reset the notifications. .
fyi @shubhi-raft @jbevis @BarakStout 

## Current behavior

-  After clearing the data, notifications are no longer shown to the user. 

## Expected behavior

- On data clear, the notifications should appear again

**Comment by jbevis** [comment] 2020-07-02 16:45
@MissyM2 can you clarify

I just reviewed the dev application and the expected behavior is what I saw.

Does this just refer to the flags for the narrative notifications in localStorage?
Because currently those would not be cleared by the clear function.

**Comment by MissyM2** [comment] 2020-07-02 17:09
@jbevis I think this is the problem.  I only saw it once.  Here is what happened.
- I asked Serena to clear the data to start a new session and see the notifications again.
- She had dev tools open and I could see the data in the app.
- She used the function that is in the app.  She tapped 'More' and 'Clear Data'
- The app did not return to the starting state and, so, could not see the notifications again.
- I saw that there seemed to be data in the graphic in devtools.
- I was not sure why but thought, maybe that Mike wrote the function to just clear anything in indexedDB.
- I was wondering if it had to do with data that you put in localStorage with regard to the notifications.
- she cleared the data from the devtools and the app returned to the starting state and could see the notifications.

**Comment by jbevis** [comment] 2020-07-02 17:15
1.) So, to that point yes, you should not see the notifications again, because that function does not clear localStorage. Is the expectation that a user would want to see those again? If so, the function needs to be updated to handle localStorage as well as indexedDB.

2.) Have you tried to replicate these steps on staging? I just went through it and after clearing the site via the clear data button I was redirected to the landing page.

Not to say what she experienced didn't happen, but we need to be able to replicate the problem consistently in order to find a solution.

**Comment by BarakStout** [comment] 2020-07-02 19:23
I am unable to replicate as well.

**Comment by BarakStout** [comment] 2020-07-02 19:35
Ticket updated to reflect the issue more accurately.

**Comment by MissyM2** [comment] 2020-07-02 19:38
@jbevis Yes, I can replicate the problem.  I tried it multiple times.  The issue is that when the user clears the data, it is expected that the system returns to the original condition and the user is able to see the notifications again.

**Comment by jbevis** [comment] 2020-07-02 20:41
@BarakStout thank you for updating the issue that expected behavior was not clear at first.

I can update the clear function to remove the notification flags as well.

**Comment by jbevis** [comment] 2020-07-02 22:14
#94 is open and ready for review.

@MissyM2 @BarakStout

**Comment by jbevis** [comment] 2020-07-06 19:47
#94 has been merged.

Closing issue.

**Closed by jbevis** 2020-07-06 19:47 UTC
Labels: bug
